# Generated by Django 2.1.2 on 2018-10-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '教师'},
        ),
    ]
