# Generated by Django 2.1.2 on 2018-10-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20181016_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['pk'], 'verbose_name_plural': '教师'},
        ),
    ]
