# Generated by Django 2.1.2 on 2018-10-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20181020_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rest_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
