# Generated by Django 2.1.2 on 2018-10-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_rest_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rest_number',
        ),
    ]
