# Generated by Django 2.1.2 on 2018-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20181104_1252'),
        ('teacher', '0008_auto_20181103_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='read_announcement',
            field=models.ManyToManyField(to='announcement.Announcement'),
        ),
    ]
