# Generated by Django 2.1.2 on 2018-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20181106_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='read_announcement',
            field=models.ManyToManyField(blank=True, to='announcement.Announcement'),
        ),
    ]
