# Generated by Django 2.1.2 on 2018-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20181108_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rest_number',
            field=models.PositiveIntegerField(default=0, verbose_name='剩余指导学生人数'),
        ),
    ]
