# Generated by Django 2.1.2 on 2018-11-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20181112_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='read_announcement',
        ),
    ]
