# Generated by Django 2.1.2 on 2018-11-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181103_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.CharField(blank=True, choices=[('teacher', '教师'), ('student', '学生')], max_length=10, null=True, verbose_name='人物'),
        ),
    ]
