# Generated by Django 2.1.2 on 2018-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181104_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_r_ann_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_r_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
