# Generated by Django 2.1.2 on 2018-11-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181108_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': '学生用户', 'verbose_name_plural': '学生用户'},
        ),
        migrations.AlterModelOptions(
            name='teacheruser',
            options={'verbose_name': '教师用户', 'verbose_name_plural': '教师用户'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
