# Generated by Django 2.1.2 on 2018-11-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181112_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='计划标题')),
                ('content', models.TextField(verbose_name='计划详细内容')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('stop_time', models.DateField(verbose_name='截至时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.CharField(blank=True, choices=[('teacher', '教师'), ('student', '学生'), ('admin', '管理员')], max_length=10, null=True, verbose_name='人物'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
