# Generated by Django 2.1.2 on 2018-11-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181113_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
