# Generated by Django 2.1.2 on 2018-11-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_plan_person'),
        ('users', '0007_auto_20181113_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_announcement',
            field=models.ManyToManyField(blank=True, to='announcement.Announcement'),
        ),
    ]
