# Generated by Django 2.1.2 on 2018-11-04 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucement',
            new_name='Announcement',
        ),
    ]
