# Generated by Django 2.1.2 on 2018-11-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20181104_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': '公告栏'},
        ),
    ]
