# Generated by Django 2.1.2 on 2018-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='person',
            field=models.CharField(choices=[('teacher', '教师'), ('student', '学生')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
