# Generated by Django 2.1.2 on 2018-11-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_plan_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pub_time'], 'verbose_name_plural': '公告栏'},
        ),
    ]
