# Generated by Django 2.1.2 on 2018-11-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20181117_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
