# Generated by Django 2.1.2 on 2018-10-16 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20181015_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '论文标签'},
        ),
        migrations.AlterField(
            model_name='thesis',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
