# Generated by Django 2.1.2 on 2018-10-17 15:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_auto_20181016_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
