# Generated by Django 2.1.2 on 2018-10-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20181017_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.AddField(
            model_name='thesis',
            name='tags',
            field=models.ManyToManyField(to='thesis.Tag'),
        ),
    ]
