# Generated by Django 2.1.2 on 2018-10-31 10:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20181019_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='选题内容'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='tags',
            field=models.ManyToManyField(to='thesis.Tag', verbose_name='选题标签'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=255, verbose_name='论文题目'),
        ),
    ]
