# Generated by Django 2.1.2 on 2018-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_auto_20181106_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='tags',
            field=models.ManyToManyField(blank=True, to='thesis.Tag', verbose_name='选题标签'),
        ),
    ]
