# Generated by Django 2.1.2 on 2018-11-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0009_auto_20181108_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='need_verify',
        ),
    ]
