# Generated by Django 2.1.2 on 2018-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_remove_thesis_need_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='need_veryfy',
            field=models.BooleanField(default=False, verbose_name='待审核'),
        ),
    ]
