# Generated by Django 2.1.2 on 2018-11-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0011_thesis_need_veryfy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='need_veryfy',
            new_name='need_verify',
        ),
    ]
