# Generated by Django 2.1.2 on 2018-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0012_auto_20181108_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='need_verify',
            field=models.BooleanField(default=True, verbose_name='待审核'),
        ),
    ]
