# Generated by Django 2.1.2 on 2018-10-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生'},
        ),
    ]
