# Generated by Django 2.1.2 on 2018-10-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('student', '0007_collection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('student', 'object_id', 'content_type')},
        ),
    ]
