# Generated by Django 2.1.2 on 2018-10-31 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20181024_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_choiced_thesis',
            field=models.BooleanField(default=False, verbose_name='是否已经选题'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher', verbose_name='指导老师'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thesis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thesis.Thesis', verbose_name='论文选题'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
