# Generated by Django 2.1.2 on 2018-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_read_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='read_announcement',
            field=models.ManyToManyField(null=True, to='announcement.Announcement'),
        ),
    ]
