# Generated by Django 2.1.2 on 2018-11-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20181108_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='read_announcement',
        ),
    ]
