# Generated by Django 2.1.2 on 2018-10-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('is_register', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'teacher_info',
                'managed': False,
            },
        ),
    ]
