# Generated by Django 2.1.2 on 2018-10-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'managed': True},
        ),
    ]
