# Generated by Django 2.1.2 on 2018-10-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0002_auto_20181017_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='is_register',
        ),
    ]
